updates.ignore = [
  // jackson 3.x, these will get updated along with jackson-core
  { groupId = "tools.jackson.core", artifactId = "jackson-databind" }
  { groupId = "tools.jackson.module" }
]

updates.pin = [
  # elasticsearch should stay on 9.x in this branch
  { groupId = "org.elasticsearch.client", version = "9."}
  # scala 2.13 should not be updated to 3.x
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.13." }
  # Scala 3.3 is an LTS
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.3." }
]
