updates.ignore = [
  // jackson 2.x, these will get updated along with jackson-core
  { groupId = "com.fasterxml.jackson.core", artifactId = "jackson-databind" }
  { groupId = "com.fasterxml.jackson.module" }
]

updates.pin = [
  # elasticsearch should stay on 8.x in this branch
  { groupId = "org.elasticsearch.client", version = "8."}
  # zio-json should stay on 0.7.x, 0.8.0+ is JDK17+
  { groupId = "dev.zio", artifactId = "zio-json", version = "0.7." }
  # scala 2.13 should stay on scala 2.13
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.13." }
  # Scala 3.3 is an LTS
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.3." }
  # scalaz 7.3+ dropped scalaz-concurrent
  { groupId = "org.scalaz", version = "7.2." }
]
