package com.sksamuel.elastic4s.analysis

object LanguageAnalyzers {
  val arabic = "arabic"
  val armenian = "armenian"
  val basque = "basque"
  val bengali = "bengali"
  val brazilian = "brazilian"
  val bulgarian = "bulgarian"
  val catalan = "catalan"
  val cjk = "cjk"
  val czech = "czech"
  val danish = "danish"
  val dutch = "dutch"
  val english = "english"
  val estonian = "estonian"
  val finnish = "finnish"
  val french = "french"
  val galician = "galician"
  val german = "german"
  val greek = "greek"
  val hindi = "hindi"
  val hungarian = "hungarian"
  val indonesian = "indonesian"
  val irish = "irish"
  val italian = "italian"
  val latvian = "latvian"
  val lithuanian = "lithuanian"
  val norwegian = "norwegian"
  val persian = "persian"
  val portuguese = "portuguese"
  val romanian = "romanian"
  val russian = "russian"
  val sorani = "sorani"
  val spanish = "spanish"
  val swedish = "swedish"
  val turkish = "turkish"
  val thai = "thai"
}
