package com.sksamuel.elastic4s.requests.analyzers

@deprecated("use new analysis package", "7.0.1")
class Analyzer(val name: String)

@deprecated("use new analysis package", "7.0.1")
case object WhitespaceAnalyzer extends Analyzer("whitespace")

@deprecated("use new analysis package", "7.0.1")
case object StandardAnalyzer   extends Analyzer("standard")

@deprecated("use new analysis package", "7.0.1")
case object SimpleAnalyzer     extends Analyzer("simple")

@deprecated("use new analysis package", "7.0.1")
case object StopAnalyzer       extends Analyzer("stop")

@deprecated("use new analysis package", "7.0.1")
case object KeywordAnalyzer    extends Analyzer("keyword")

@deprecated("use new analysis package", "7.0.1")
case object PatternAnalyzer    extends Analyzer("pattern")

@deprecated("Use the language-specific analyzer in modules/analysis instead", "5.0.0")
case object SnowballAnalyzer extends Analyzer("snowball")

@deprecated("use new analysis package", "7.0.1")
case class CustomAnalyzer(override val name: String) extends Analyzer(name)

@deprecated("use new analysis package", "7.0.1")
class LanguageAnalyzer(name: String) extends Analyzer(name: String)

@deprecated("use new analysis package", "7.0.1")
case object ArabicLanguageAnalyzer     extends LanguageAnalyzer("arabic")

@deprecated("use new analysis package", "7.0.1")
case object ArmenianLanguageAnalyzer   extends LanguageAnalyzer("armenian")

@deprecated("use new analysis package", "7.0.1")
case object BasqueLanguageAnalyzer extends LanguageAnalyzer("basque")
@deprecated("use new analysis package", "7.0.1")
case object BrazilianLanguageAnalyzer extends LanguageAnalyzer("brazilian")
@deprecated("use new analysis package", "7.0.1")
case object BulgarianLanguageAnalyzer extends LanguageAnalyzer("bulgarian")
@deprecated("use new analysis package", "7.0.1")
case object CatalanLanguageAnalyzer extends LanguageAnalyzer("catalan")
@deprecated("use new analysis package", "7.0.1")
case object ChineseLanguageAnalyzer extends LanguageAnalyzer("chinese")
@deprecated("use new analysis package", "7.0.1")
case object CjkLanguageAnalyzer extends LanguageAnalyzer("cjk")
@deprecated("use new analysis package", "7.0.1")
case object CzechLanguageAnalyzer extends LanguageAnalyzer("czech")
@deprecated("use new analysis package", "7.0.1")
case object DanishLanguageAnalyzer extends LanguageAnalyzer("danish")
@deprecated("use new analysis package", "7.0.1")
case object DutchLanguageAnalyzer      extends LanguageAnalyzer("dutch")
@deprecated("use new analysis package", "7.0.1")
case object EnglishLanguageAnalyzer    extends LanguageAnalyzer("english")
@deprecated("use new analysis package", "7.0.1")
case object FinnishLanguageAnalyzer    extends LanguageAnalyzer("finnish")
@deprecated("use new analysis package", "7.0.1")
case object FrenchLanguageAnalyzer     extends LanguageAnalyzer("french")
@deprecated("use new analysis package", "7.0.1")
case object GalicianLanguageAnalyzer   extends LanguageAnalyzer("galician")
@deprecated("use new analysis package", "7.0.1")
case object GermanLanguageAnalyzer     extends LanguageAnalyzer("german")
@deprecated("use new analysis package", "7.0.1")
case object GreekLanguageAnalyzer      extends LanguageAnalyzer("greek")
@deprecated("use new analysis package", "7.0.1")
case object HindiLanguageAnalyzer extends LanguageAnalyzer("hindi")
@deprecated("use new analysis package", "7.0.1")
case object HungarianLanguageAnalyzer extends LanguageAnalyzer("hungarian")
@deprecated("use new analysis package", "7.0.1")
case object IndonesianLanguageAnalyzer extends LanguageAnalyzer("indonesian")
@deprecated("use new analysis package", "7.0.1")
case object IrishLanguageAnalyzer extends LanguageAnalyzer("irish")
@deprecated("use new analysis package", "7.0.1")
case object ItalianLanguageAnalyzer extends LanguageAnalyzer("italian")
@deprecated("use new analysis package", "7.0.1")
case object LatvianLanguageAnalyzer extends LanguageAnalyzer("latvian")
@deprecated("use new analysis package", "7.0.1")
case object LithuanianLanguageAnalyzer extends LanguageAnalyzer("lithuanian")
@deprecated("use new analysis package", "7.0.1")
case object NorwegianLanguageAnalyzer extends LanguageAnalyzer("norwegian")
@deprecated("use new analysis package", "7.0.1")
case object PersianLanguageAnalyzer extends LanguageAnalyzer("persian")
@deprecated("use new analysis package", "7.0.1")
case object PortugueseLanguageAnalyzer extends LanguageAnalyzer("portuguese")
@deprecated("use new analysis package", "7.0.1")
case object RomanianLanguageAnalyzer extends LanguageAnalyzer("romanian")
@deprecated("use new analysis package", "7.0.1")
case object RussianLanguageAnalyzer extends LanguageAnalyzer("russian")
@deprecated("use new analysis package", "7.0.1")
case object SoraniLanguageAnalyzer extends LanguageAnalyzer("sorani")
@deprecated("use new analysis package", "7.0.1")
case object SpanishLanguageAnalyzer extends LanguageAnalyzer("spanish")
@deprecated("use new analysis package", "7.0.1")
case object SwedishLanguageAnalyzer extends LanguageAnalyzer("swedish")
@deprecated("use new analysis package", "7.0.1")
case object TurkishLanguageAnalyzer extends LanguageAnalyzer("turkish")
@deprecated("use new analysis package", "7.0.1")
case object ThaiLanguageAnalyzer       extends LanguageAnalyzer("thai")
