package com.sksamuel.elastic4s

/** @author Stephen Samuel */
abstract class Analyzer(val elastic: String)
object Analyzer {
  case object NotAnalyzed extends Analyzer("notindexed")
  case object WhitespaceAnalyzer extends Analyzer("whitespace")
  case object StandardAnalyzer extends Analyzer("standard")
  case object SimpleAnalyzer extends Analyzer("simple")
  case object StopAnalyzer extends Analyzer("stop")
  case object KeywordAnalyzer extends Analyzer("keyword")
  case object PatternAnalyzer extends Analyzer("pattern")
  case object SnowballAnalyzer extends Analyzer("snowball")

  //language analyzers
  case object ArabicAnalyzer extends Analyzer("arabic")
  case object ArmenianAnalyzer extends Analyzer("armenian")
  case object BasqueAnalyzer extends Analyzer("basque")
  case object BrazilianAnalyzer extends Analyzer("brazilian")
  case object BulgarianAnalyzer extends Analyzer("bulgarian")
  case object CatalanAnalyzer extends Analyzer("catalan")
  case object ChineseAnalyzer extends Analyzer("chinese")
  case object CjkAnalyzer extends Analyzer("cjk")
  case object CzechAnalyzer extends Analyzer("czech")
  case object DanishAnalyzer extends Analyzer("danish")
  case object DutchAnalyzer extends Analyzer("dutch")
  case object EnglishAnalyzer extends Analyzer("english")
  case object FinnishAnalyzer extends Analyzer("finnish")
  case object FrenchAnalyzer extends Analyzer("french")
  case object GalicianAnalyzer extends Analyzer("galician")
  case object GermanAnalyzer extends Analyzer("german")
  case object GreekAnalyzer extends Analyzer("greek")
  case object HindiAnalyzer extends Analyzer("hindi")
  case object HungarianAnalyzer extends Analyzer("hungarian")
  case object IndonesianAnalyzer extends Analyzer("indonesian")
  case object ItalianAnalyzer extends Analyzer("italian")
  case object LatvianAnalyzer extends Analyzer("latvian")
  case object NorwegianAnalyzer extends Analyzer("norwegian")
  case object PersianAnalyzer extends Analyzer("persian")
  case object PortugueseAnalyzer extends Analyzer("portuguese")
  case object RomanianAnalyzer extends Analyzer("romanian")
  case object RussianAnalyzer extends Analyzer("russian")
  case object SpanishAnalyzer extends Analyzer("spanish")
  case object SwedishAnalyzer extends Analyzer("swedish")
  case object TurkishAnalyzer extends Analyzer("turkish")
  case object ThaiAnalyzer extends Analyzer("thai")
}