name: build

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches:
      - series/9.x

jobs:
  scala-2_13:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: set up sbt
        uses: sbt/setup-sbt@v1

      - name: Launch elastic docker
        uses: ./.github/actions/launch-elasticsearch

      - name: run tests
        run: sbt ++2.13.16 test

  scala-3_0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: set up sbt
        uses: sbt/setup-sbt@v1

      - name: Launch elastic docker
        uses: ./.github/actions/launch-elasticsearch

      - name: run tests
        run: sbt ++3.3.4 elastic4s-scala3/test
